"""Export a volume as a Word document, generated from its chapters.

    python3 scripts/make_docx.py [volume-slug] [out.docx]

Built from the chapters, not from the original draft, so it says what the
course currently says rather than what it used to.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from build import chapter_files, find_volume, split_blocks      # noqa: E402

from docx import Document                                       # noqa: E402
from docx.enum.text import WD_ALIGN_PARAGRAPH                   # noqa: E402
from docx.shared import Pt, RGBColor, Inches                    # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

# Which volume, and where its Word file goes. A volume slug may be given first;
# without one there had better be only a single volume to mean.
_args = [a for a in sys.argv[1:] if not a.endswith(".docx")]
VOLUME = find_volume(_args[0] if _args else None)
TITLE = ": ".join(x for x in (VOLUME["title"], VOLUME.get("subtitle")) if x)


def add_runs(paragraph, text):
    """Inline markdown: `code`, **bold**, *italic*, [links](x)."""
    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r"\1", text)
    for piece in re.split(r"(`[^`]+`|\*\*[^*]+\*\*|(?<!\*)\*[^*]+\*(?!\*))", text):
        if not piece:
            continue
        if piece.startswith("`") and piece.endswith("`"):
            run = paragraph.add_run(piece[1:-1])
            run.font.name = "Menlo"
            run.font.size = Pt(9.5)
            run.font.color.rgb = RGBColor(0x8A, 0x30, 0x20)
        elif piece.startswith("**"):
            paragraph.add_run(piece[2:-2]).bold = True
        elif piece.startswith("*"):
            paragraph.add_run(piece[1:-1]).italic = True
        else:
            paragraph.add_run(piece)


def add_code(document, code, muted=False):
    paragraph = document.add_paragraph()
    paragraph.paragraph_format.left_indent = Inches(0.3)
    paragraph.paragraph_format.space_before = Pt(6)
    paragraph.paragraph_format.space_after = Pt(6)
    run = paragraph.add_run(code.rstrip("\n"))
    run.font.name = "Menlo"
    run.font.size = Pt(9)
    if muted:
        run.font.color.rgb = RGBColor(0x60, 0x60, 0x60)


def main():
    named = [a for a in sys.argv[1:] if a.endswith(".docx")]
    out = (Path(named[0]) if named else
           ROOT / "site" / VOLUME["slug"] / VOLUME.get("docx", f"{VOLUME['slug']}.docx"))
    document = Document()

    document.core_properties.title = TITLE
    document.core_properties.author = "Justin Stewart"
    document.core_properties.comments = "generated by python-docx. Claude Opus 5"

    style = document.styles["Normal"]
    style.font.name = "Georgia"
    style.font.size = Pt(11)

    seen_parts = set()
    # chapter_files() rather than a raw glob: it drops the underscore-prefixed
    # build inputs -- _solutions.md holds every worked answer -- and orders the
    # appendices after the chapters instead of after the front matter.
    for path in chapter_files(VOLUME):
        text = path.read_text()
        part = None
        if text.startswith("<!--"):
            part = re.match(r"<!-- part: (.+) -->", text).group(1)
            text = text.split("\n", 1)[1]

        if part and part not in seen_parts:
            seen_parts.add(part)
            document.add_page_break()
            heading = document.add_paragraph(part)
            heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
            heading.runs[0].bold = True
            heading.runs[0].font.size = Pt(20)
        elif path.stem != "00-front-matter":
            document.add_page_break()

        for kind, payload in split_blocks(text.split("\n")):
            if kind == "h1":
                document.add_heading(payload, 0)
            elif kind == "h2":
                document.add_heading(re.sub(r"`", "", payload), 1)
            elif kind == "h3":
                document.add_heading(re.sub(r"`", "", payload), 2)
            elif kind == "p":
                add_runs(document.add_paragraph(), payload)
            elif kind == "code":
                add_code(document, payload)
            elif kind == "output":
                add_code(document, payload, muted=True)
            elif kind in ("ol", "ul"):
                for item in payload:
                    style_name = "List Number" if kind == "ol" else "List Bullet"
                    add_runs(document.add_paragraph(style=style_name), item)
            elif kind == "quote":
                add_runs(document.add_paragraph(style="Intense Quote"), payload)
            elif kind == "table":
                cells = [[c.strip() for c in r.strip("|").split("|")] for r in payload]
                table = document.add_table(rows=0, cols=len(cells[0]))
                table.style = "Light Grid Accent 1"
                for n, row in enumerate(cells):
                    if n == 1:
                        continue                       # the |---| separator
                    cursor = table.add_row().cells
                    for cell, value in zip(cursor, row):
                        cell.text = ""
                        add_runs(cell.paragraphs[0], value)
                        if n == 0:
                            for run in cell.paragraphs[0].runs:
                                run.bold = True

    out.parent.mkdir(parents=True, exist_ok=True)
    document.save(out)
    try:
        shown = out.relative_to(ROOT)
    except ValueError:
        shown = out
    print(f"{shown}  {out.stat().st_size:,} bytes")


if __name__ == "__main__":
    main()
